# Generated by Django 4.1.3 on 2024-02-24 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0051_revisorescata_b10_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='nivel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='investigadores.nivelinvestigador'),
        ),
    ]
