# Generated by Django 4.1.3 on 2024-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0052_alter_investigador_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='mensajes_no_leidos',
            field=models.IntegerField(default=0),
        ),
    ]
