# Generated by Django 4.1.3 on 2024-03-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0007_alter_noticia_fecha'),
        ('investigadores', '0054_remove_investigador_mensajes_no_leidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='area_conocimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vinculacion.areaconocimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigador',
            name='telefono',
            field=models.CharField(default=1, max_length=10, verbose_name='Telefono'),
            preserve_default=False,
        ),
    ]
