# Generated by Django 4.1.3 on 2024-03-15 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_municipio'),
        ('investigadores', '0055_investigador_area_conocimiento_investigador_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.municipio'),
        ),
    ]
