# Generated by Django 4.1.3 on 2024-04-26 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0056_alter_investigador_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='curp',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(code='curp_invalido', message='El CURP no tiene un formato válido', regex='^([A-Z][AEIOUX][A-Z]{2}\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\\d])(\\d)$')], verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Telefono de contacto para futuras colaboraciones'),
        ),
    ]
