# Generated by Django 4.1.3 on 2024-05-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0057_alter_investigador_curp_alter_investigador_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, verbose_name='Telefono de contacto para futuras colaboraciones'),
        ),
    ]
