# Generated by Django 4.1.3 on 2024-06-19 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0008_alter_areaconocimiento_nombre'),
        ('investigadores', '0059_alter_investigador_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='area_conocimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vinculacion.areaconocimiento'),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono de contacto para futuras colaboraciones'),
        ),
    ]
