# Generated by Django 4.1.3 on 2024-03-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_user_es_revisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mensajes_no_leidos',
            field=models.IntegerField(default=0),
        ),
    ]
