# Generated by Django 4.1.3 on 2024-03-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_user_mensajes_no_leidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mensajes_no_leidos',
        ),
    ]
