# Generated by Django 4.1.3 on 2024-04-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0007_alter_noticia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaconocimiento',
            name='nombre',
            field=models.CharField(max_length=70, verbose_name='Area del conocimiento'),
        ),
    ]
