# Generated by Django 4.1.3 on 2024-05-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones_educativas', '0014_alter_institucioneducativa_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='email',
            field=models.EmailField(default='ljuan0791@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='telefono',
            field=models.CharField(default='4921416654', max_length=10, verbose_name='Telefono de contacto para futuras colaboraciones'),
            preserve_default=False,
        ),
    ]
