# Generated by Django 4.1.3 on 2024-05-28 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0008_alter_areaconocimiento_nombre'),
        ('instituciones_educativas', '0015_institucioneducativa_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='area_conocimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vinculacion.areaconocimiento'),
            preserve_default=False,
        ),
    ]
