# Generated by Django 4.1.3 on 2024-03-14 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_municipio'),
        ('empresas', '0016_alter_empresa_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.municipio', verbose_name='Municipio'),
        ),
    ]
