# Generated by Django 4.1.3 on 2024-03-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0007_alter_noticia_fecha'),
        ('empresas', '0017_alter_empresa_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='especialidades',
            field=models.ManyToManyField(blank=True, to='vinculacion.areaconocimiento', verbose_name='Area del conocimiento'),
        ),
    ]
