# Generated by Django 4.1.3 on 2024-04-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0018_alter_empresa_especialidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='numero_exterior',
            field=models.CharField(max_length=10, verbose_name='Numero Exterior'),
        ),
    ]
