# Generated by Django 4.1.3 on 2024-06-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0020_empresa_email_empresa_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo_institucion',
            field=models.CharField(default='', max_length=250, verbose_name='Tipo Institucion'),
            preserve_default=False,
        ),
    ]
