# Generated by Django 4.1.3 on 2024-06-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0022_alter_empresa_tipo_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tipo_institucion',
            field=models.IntegerField(choices=[(0, 'Empresa'), (1, 'Centro de Investigación'), (2, 'Institución Pública')], verbose_name='Tipo Institucion'),
        ),
    ]
